// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLk9YNxHEIfdBgQrJMw_w0dLJmMrpljpY',
    appId: '1:160297552831:web:2463b961c82f09205daf0a',
    messagingSenderId: '160297552831',
    projectId: 'thesis-rotify',
    authDomain: 'thesis-rotify.firebaseapp.com',
    databaseURL: 'https://thesis-rotify-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-rotify.firebasestorage.app',
    measurementId: 'G-X0HHK31K0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6TZ_Fgx2QB2_rJQpaHE_Ya3CydG6Z_A',
    appId: '1:160297552831:android:f52345132a020b465daf0a',
    messagingSenderId: '160297552831',
    projectId: 'thesis-rotify',
    databaseURL: 'https://thesis-rotify-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-rotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhnnVYBZ_esAKKZSoV6QIf7pQGyuSQgQ',
    appId: '1:160297552831:ios:d0172932e7426bea5daf0a',
    messagingSenderId: '160297552831',
    projectId: 'thesis-rotify',
    databaseURL: 'https://thesis-rotify-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-rotify.firebasestorage.app',
    iosBundleId: 'com.example.rotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAhnnVYBZ_esAKKZSoV6QIf7pQGyuSQgQ',
    appId: '1:160297552831:ios:d0172932e7426bea5daf0a',
    messagingSenderId: '160297552831',
    projectId: 'thesis-rotify',
    databaseURL: 'https://thesis-rotify-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-rotify.firebasestorage.app',
    iosBundleId: 'com.example.rotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLk9YNxHEIfdBgQrJMw_w0dLJmMrpljpY',
    appId: '1:160297552831:web:e11b31a60e7c14575daf0a',
    messagingSenderId: '160297552831',
    projectId: 'thesis-rotify',
    authDomain: 'thesis-rotify.firebaseapp.com',
    databaseURL: 'https://thesis-rotify-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-rotify.firebasestorage.app',
    measurementId: 'G-NBFRD9Q0DQ',
  );
}
